#!/bin/sh
test "$HAS_POWERLINE" -eq "1" && roa='' || roa='«'
$TMUX_PLUGIN_MANAGER_PATH/tmux-mem-cpu-load/tmux-mem-cpu-load \
  --graph-lines 0 \
  --cpu-mode 1 \
  --interval 1 \
  --averages-count 1 \
  #| sed "s/\(.*MB\)  \(.*%\) \(.*\)/MEM: \1 ${roa} CPU: \2 ${roa} load: \3/"
