#!/bin/bash
test "$HAS_POWERLINE" -eq "1" && roa='' || roa='«'
RXB=0
TXB=0

for rxbytes in /sys/class/net/*/statistics/rx_bytes ; do
  let RXB+=$(<$rxbytes)
done

for txbytes in /sys/class/net/*/statistics/tx_bytes ; do
  let TXB+=$(<$txbytes)
done

sleep 2 

RXBN=0
TXBN=0

for rxbytes in /sys/class/net/*/statistics/rx_bytes ; do
  let RXBN+=$(<$rxbytes)
done

for txbytes in /sys/class/net/*/statistics/tx_bytes ; do
  let TXBN+=$(<$txbytes)
done    

RXDIF=$(echo $((RXBN - RXB)) )
TXDIF=$(echo $((TXBN - TXB)) )

test "$HAS_POWERLINE" -eq "1" && { dl='' && ul=''; } || { dl='d' && ul='u'; }

echo -e "$roa #[fg=colour2]$dl$((RXDIF / 1024 / 2))#[fg=colour160] $ul$((TXDIF / 1024 / 2)) "
exit 0
