$recorder = 1;
$pdf_mode = 1;
$bibtex_use = 2;
$pdflatex = "pdflatex -synctex=1 -interaction=nonstopmode %S";
$pdf_previewer = "start open -a Skim %O %S";
@generated_exts = (@generated_exts, 'synctex.gz');
$clean_ext .= 'abr  abv  glsdefs  nlg  nlo  nls  sbl  slg  sym acn alg glr brf glo glg gls';

$clean_ext .= ' %R.ist %R.xdy';
